
"use client";

import type { Metadata } from "next";
import { useContext } from "react";
import { AuthContext } from "@/app/auth-provider";

export const metadata: Metadata = {
  title: 'About Page',
  description: 'About Page generated by create next app',
}

export default function About() {
  const { user } = useContext(AuthContext);
  return (
    <main className="flex flex-col items-center justify-between p-4">
      <h1 className='text-xl mb-16'>About Page</h1>
      {user && <h2 className="text-xl mb-16">{`Welcome back ${user?.firstName}:)`}</h2>}
    </main>
  )
}
