
import type { Metadata } from "next";
import User from "@/component/User";
import Login from "@/component/Login";

export const metadata: Metadata = {
  title: "Login Page",
  description: "Login Page generated by create next app",
};

export default function LoginPage() {
  return (
    <main className="flex flex-col items-center justify-between p-4">
      <h1 className="text-xl mb-16">Login Page</h1>
      <User />
      <Login />
    </main>
  );
}
