"use client";

import type { Metadata } from "next";
import { useContext } from "react";
import { AuthContext } from "@/app/auth-provider";

export const metadata: Metadata = {
  title: "Login Page",
  description: "Login Page generated by create next app",
};

export default function Login() {
  const { user, setUser } = useContext(AuthContext);

  const handleFetchData = async () => {
    const response = await fetch("https://dummyjson.com/users/1");
    if (response.status == 200) {
      const data = await response.json();
      setUser(data) ;
    }
  };

  return (
    <main className="flex flex-col items-center justify-between p-4">
      <h1 className="text-xl mb-16">Login Page</h1>
      {user && <h2 className="text-xl mb-16">{`Welcome back ${user?.firstName}:)`}</h2>}
      <button onClick={handleFetchData}>Login Action</button>
    </main>
  );
}
