import type { Metadata } from "next";
import User from "@/component/User";

export const metadata: Metadata = {
  title: "Home Page",
  description: "Home Page generated by create next app",
};

export default function Home() {
  return (
    <main className="flex flex-col items-center justify-between p-4">
      <h1 className="text-xl mb-16">Home Page</h1>
      <User />
    </main>
  );
}
